use_frameworks!

target 'CDVRequest_Example' do
  pod 'CDVRequest', :path => '../'

  target 'CDVRequest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
